# Generated by Django 4.1.7 on 2023-04-04 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mueble',
            name='precio',
            field=models.FloatField(default=''),
        ),
    ]
