# Generated by Django 4.1.7 on 2023-04-08 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_mueble_imagen_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='mueble',
            name='oferta',
            field=models.BooleanField(default='False'),
        ),
        migrations.AlterField(
            model_name='mueble',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='core\\static\\images'),
        ),
    ]
